import { useRef, useState, type CompositionEvent, type KeyboardEvent } from 'react'
import type { ActionCardView, DecisionCardView, GuidedLearningCardView, OfflineTaskCardView, QuestionCardView, ReviewCardView } from '../../domain/structured-results.ts'
import { copy } from '../copy.ts'
import { DrawerController, useDrawer } from '../state.ts'

function Details({ card }: { card: ActionCardView }) { return card.details.length === 0 ? null : <details className="dsh-learning-details"><summary>查看依据</summary>{card.details.map(detail => <section key={detail.label}><h4>{detail.label}</h4><p>{detail.body}</p></section>)}</details> }

export function EvidenceComposer({ controller, draftKey, review = false, inputHint, exampleSkeleton, onSubmit }: { controller: DrawerController; draftKey: string; review?: boolean; inputHint?: string; exampleSkeleton?: string; onSubmit: () => void }) {
  const state = useDrawer(controller); const t = copy[state.locale]
  const [value, setValue] = useState(() => controller.getDraft(draftKey)); const composing = useRef(false)
  const running = state.operation === 'running'
  const submit = () => { if (value.trim() !== '' && !running) onSubmit() }
  const useExample = () => { if (!exampleSkeleton || running) return; setValue(exampleSkeleton); controller.setDraft(draftKey, exampleSkeleton) }
  const onKeyDown = (event: KeyboardEvent<HTMLTextAreaElement>) => { if ((event.ctrlKey || event.metaKey) && event.key === 'Enter' && !composing.current && !event.nativeEvent.isComposing) { event.preventDefault(); submit() } }
  return <>{inputHint ? <div className="dsh-learning-input-hint"><strong>{t.inputHint}</strong><p>{inputHint}</p></div> : null}{exampleSkeleton && value.trim() === '' ? <div className="dsh-learning-example"><strong>{t.exampleLabel}</strong><p>{exampleSkeleton}</p><button type="button" className="dsh-learning-text-button" disabled={running} onClick={useExample}>{t.useExample}</button></div> : null}<label className="dsh-learning-label" htmlFor={`evidence-${draftKey}`}>{t.evidence}</label><textarea id={`evidence-${draftKey}`} className="dsh-learning-input" value={value} placeholder={exampleSkeleton} disabled={running} onChange={(event) => { setValue(event.currentTarget.value); controller.setDraft(draftKey, event.currentTarget.value) }} onCompositionStart={(_event: CompositionEvent) => { composing.current = true }} onCompositionEnd={(_event: CompositionEvent) => { composing.current = false }} onKeyDown={onKeyDown} /><p className="dsh-learning-meta">{t.saveNote}</p>{running ? <div className="dsh-learning-processing" role="status" aria-live="polite"><strong>{t.checkingEvidence}</strong><span>{t.checkingHelp}</span></div> : null}<div className="dsh-learning-actions"><button data-primary-action className="dsh-learning-primary" type="button" disabled={value.trim() === '' || running} onClick={submit}>{running ? t.checkingEvidence : review ? t.submitReview : t.submitEvidence}</button></div></>
}

function QuestionCard({ controller, card, onSubmit }: { controller: DrawerController; card: QuestionCardView; onSubmit: () => void }) { const { locale } = useDrawer(controller); const t = copy[locale]; return <article><div className="dsh-learning-callout">{card.prompt}</div><EvidenceComposer controller={controller} draftKey={card.cardId} onSubmit={onSubmit} /><Details card={card} /><span className="dsh-learning-live">{t.answer}</span></article> }
function GuidedLearningCard({ controller, card, onSubmit }: { controller: DrawerController; card: GuidedLearningCardView; onSubmit: () => void }) { return <article><div className="dsh-learning-callout">{card.explanation}</div>{card.prompt ? <p><strong>{card.prompt}</strong></p> : null}{card.input ? <EvidenceComposer controller={controller} draftKey={card.cardId} onSubmit={onSubmit} /> : <button data-primary-action type="button" className="dsh-learning-primary" onClick={onSubmit}>我已完成讲回</button>}<Details card={card} /></article> }
function DecisionCard({ controller, card, onSubmit }: { controller: DrawerController; card: DecisionCardView; onSubmit: () => void }) { const { locale } = useDrawer(controller); const t = copy[locale]; return <article><div className="dsh-learning-callout"><strong>{card.recommendation}</strong></div><h4>依据</h4><ul className="dsh-learning-list">{card.basis.map(item => <li key={item}>{item}</li>)}</ul><h4>代价和边界</h4><ul className="dsh-learning-list">{card.boundaries.map(item => <li key={item}>{item}</li>)}</ul>{card.editableFields.map(field => <label className="dsh-learning-label" key={field.key}>{field.label}<input className="dsh-learning-input" defaultValue={field.value} /></label>)}<div className="dsh-learning-actions"><button data-primary-action className="dsh-learning-primary" type="button" onClick={onSubmit}>{t.confirm}</button></div></article> }
function OfflineTaskCard({ controller, card, onSubmit }: { controller: DrawerController; card: OfflineTaskCardView; onSubmit: () => void }) { return <article><h4>任务说明</h4><ol className="dsh-learning-list">{card.instructions.map(item => <li key={item}>{item}</li>)}</ol><h4>提交时需要</h4><ul className="dsh-learning-list">{card.evidenceRequirements.map(item => <li key={item}>{item}</li>)}</ul><EvidenceComposer controller={controller} draftKey={card.cardId} onSubmit={onSubmit} /></article> }
function ReviewCard({ controller, card, onSubmit }: { controller: DrawerController; card: ReviewCardView; onSubmit: () => void }) { return <article><div className="dsh-learning-callout"><strong>{card.claim}</strong><p>{card.prompt}</p></div><p className="dsh-learning-meta">参考内容会在提交后显示，先凭自己的理解完成。</p><EvidenceComposer controller={controller} draftKey={card.cardId} review onSubmit={onSubmit} /></article> }

export function ActionCard({ controller, card, onSubmit }: { controller: DrawerController; card: ActionCardView; onSubmit: () => void }) {
  if (card.kind === 'question') return <QuestionCard controller={controller} card={card} onSubmit={onSubmit} />
  if (card.kind === 'guided-learning') return <GuidedLearningCard controller={controller} card={card} onSubmit={onSubmit} />
  if (card.kind === 'decision') return <DecisionCard controller={controller} card={card} onSubmit={onSubmit} />
  if (card.kind === 'offline-task') return <OfflineTaskCard controller={controller} card={card} onSubmit={onSubmit} />
  return <ReviewCard controller={controller} card={card} onSubmit={onSubmit} />
}
